//go:build go1.22

// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apispec

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	HmacAuthScopes = "HmacAuth.Scopes"
)

// Defines values for PaymentIntentState.
const (
	Completed PaymentIntentState = "completed"
	Expired   PaymentIntentState = "expired"
	Failed    PaymentIntentState = "failed"
	Funded    PaymentIntentState = "funded"
	PaidOut   PaymentIntentState = "paid_out"
	Pending   PaymentIntentState = "pending"
	Settling  PaymentIntentState = "settling"
)

// Valid indicates whether the value is a known member of the PaymentIntentState enum.
func (e PaymentIntentState) Valid() bool {
	switch e {
	case Completed:
		return true
	case Expired:
		return true
	case Failed:
		return true
	case Funded:
		return true
	case PaidOut:
		return true
	case Pending:
		return true
	case Settling:
		return true
	default:
		return false
	}
}

// CreatePaymentIntentRequest defines model for CreatePaymentIntentRequest.
type CreatePaymentIntentRequest struct {
	// AmountIdr Amount in IDR minor units (rupiah; IDR has no sub-unit).
	AmountIdr   int64   `json:"amount_idr"`
	Description *string `json:"description,omitempty"`

	// ExternalRef Merchant-supplied deterministic id; unique per merchant.
	ExternalRef string `json:"external_ref"`
}

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// PaymentIntent defines model for PaymentIntent.
type PaymentIntent struct {
	AmountIdr   int64              `json:"amount_idr"`
	CreatedAt   time.Time          `json:"created_at"`
	ExternalRef string             `json:"external_ref"`
	Id          openapi_types.UUID `json:"id"`
	MerchantId  openapi_types.UUID `json:"merchant_id"`
	Quote       Quote              `json:"quote"`

	// QuotedAmountUsdc USDC amount in minor units (1e-6 USDC; SPL decimals=6).
	QuotedAmountUsdc int64 `json:"quoted_amount_usdc"`

	// ReferencePubkey Populated once Solana Pay allocation runs (phase 3+).
	ReferencePubkey *string            `json:"reference_pubkey,omitempty"`
	State           PaymentIntentState `json:"state"`
}

// PaymentIntentState defines model for PaymentIntent.State.
type PaymentIntentState string

// Quote defines model for Quote.
type Quote struct {
	ExpiresAt time.Time          `json:"expires_at"`
	Id        openapi_types.UUID `json:"id"`
	Pair      string             `json:"pair"`

	// Rate Decimal string to avoid float round-trip (e.g. "0.0000617").
	Rate      string `json:"rate"`
	SpreadBps int32  `json:"spread_bps"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// CreatePaymentIntentParams defines parameters for CreatePaymentIntent.
type CreatePaymentIntentParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreatePaymentIntentJSONRequestBody defines body for CreatePaymentIntent for application/json ContentType.
type CreatePaymentIntentJSONRequestBody = CreatePaymentIntentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// Create a payment intent
	// (POST /v1/payment_intents)
	CreatePaymentIntent(w http.ResponseWriter, r *http.Request, params CreatePaymentIntentParams)
	// Fetch a payment intent by id
	// (GET /v1/payment_intents/{id})
	GetPaymentIntent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) CreatePaymentIntent(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, HmacAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePaymentIntentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePaymentIntent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentIntent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HmacAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPaymentIntent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc("POST "+options.BaseURL+"/v1/payment_intents", wrapper.CreatePaymentIntent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/payment_intents/{id}", wrapper.GetPaymentIntent)

	return m
}

type ErrorJSONResponse Error

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200TextResponse string

func (response Healthz200TextResponse) VisitHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type CreatePaymentIntentRequestObject struct {
	Params CreatePaymentIntentParams
	Body   *CreatePaymentIntentJSONRequestBody
}

type CreatePaymentIntentResponseObject interface {
	VisitCreatePaymentIntentResponse(w http.ResponseWriter) error
}

type CreatePaymentIntent201JSONResponse PaymentIntent

func (response CreatePaymentIntent201JSONResponse) VisitCreatePaymentIntentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreatePaymentIntent400JSONResponse struct{ ErrorJSONResponse }

func (response CreatePaymentIntent400JSONResponse) VisitCreatePaymentIntentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePaymentIntent401JSONResponse Error

func (response CreatePaymentIntent401JSONResponse) VisitCreatePaymentIntentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreatePaymentIntent409JSONResponse Error

func (response CreatePaymentIntent409JSONResponse) VisitCreatePaymentIntentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetPaymentIntentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPaymentIntentResponseObject interface {
	VisitGetPaymentIntentResponse(w http.ResponseWriter) error
}

type GetPaymentIntent200JSONResponse PaymentIntent

func (response GetPaymentIntent200JSONResponse) VisitGetPaymentIntentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPaymentIntent404JSONResponse struct{ ErrorJSONResponse }

func (response GetPaymentIntent404JSONResponse) VisitGetPaymentIntentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// Create a payment intent
	// (POST /v1/payment_intents)
	CreatePaymentIntent(ctx context.Context, request CreatePaymentIntentRequestObject) (CreatePaymentIntentResponseObject, error)
	// Fetch a payment intent by id
	// (GET /v1/payment_intents/{id})
	GetPaymentIntent(ctx context.Context, request GetPaymentIntentRequestObject) (GetPaymentIntentResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePaymentIntent operation middleware
func (sh *strictHandler) CreatePaymentIntent(w http.ResponseWriter, r *http.Request, params CreatePaymentIntentParams) {
	var request CreatePaymentIntentRequestObject

	request.Params = params

	var body CreatePaymentIntentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePaymentIntent(ctx, request.(CreatePaymentIntentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePaymentIntent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePaymentIntentResponseObject); ok {
		if err := validResponse.VisitCreatePaymentIntentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPaymentIntent operation middleware
func (sh *strictHandler) GetPaymentIntent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPaymentIntentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPaymentIntent(ctx, request.(GetPaymentIntentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPaymentIntent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPaymentIntentResponseObject); ok {
		if err := validResponse.VisitGetPaymentIntentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RX3W7bOhJ+lQF3L1KsbMtJk20V7EU22W6Cpmgat8ACceDS4jhiS5EMOXLjLfxQ5xXO",
	"kx2Q8p9sNUkPenpTRRpyvvnmmx9/Z7kprdGoybPsO7Pc8RIJXfzrQmBpDaHOZ29xFt5IzTJWIBfoWMI0",
	"L5Flm2adYJcwnxdY8nCg5A+XqO+oYNn+4WHCaGbDEU9O6js2n88T5tBboz1Gl/9xzrjwkBtNqCk8cmuV",
	"zDlJo3tfvNHh3drD3x1OWMb+1ltH0qu/+l59W/Qi0OdO2nAJy9iVM2OFJSx9s2CyOBUuPXXICa/4rERN",
	"FxHJNd5X6CMg64xFR7KGzEtTaRpJEXE3/ZzEbyA1XJxdQym1cVBpSR72XGUlL47jh4J70AZ8Ne6Ery+6",
	"LGET40pOLGNS09FLlrBSallWJcv6KxqlJrxDx7bja/B+mKY7vCcMHwid5moU6dvG/Q5dXnBNHV8F8lGA",
	"CKoIEDzJHKQ4DnHcVwgWHZQL84B7w3N//1WEvfp7N/8h/feVdChYdtMElWwye7s6asZfMKcQwkorzXzk",
	"RmD4Hx94aVVN05QrKUZukcIWOgQSl6rOpxAy0MDV1ca95CpswVCi9/wu+ns8tIhqbd8WT0NuT+lsRx67",
	"ksijiMWIU+OA4IQdkiWyZ8hix0CKxmVVJUXbPUtFjJ5pf18ZwqfK+UM0WlqL0YKRyot8V8KfBmenwFf1",
	"16i9PnaOIBgcw+DqEgTmsuTK/+uovfJ2qXU4QYc6x5Gtxl/r3rjVYYytVKAfjM4RBkZxzeGKz4ArZepu",
	"Bq7SHvZswT3CwT+ic10pxcdBtg3FrZnyxGumUIdmcMMsahG+JWxSaYGBXo9Eqn5nuRQjUwXRB0YVUrTA",
	"BxuVmbAJlwrFhiB/IOCYt820Jo+Ua2uKlllextBQaFtBfFiKolkINXb/U7p+pgwtl67ZOy7OrntBKW3W",
	"bpGJZubPajVBbQdkgE+NFDBRhhM4U2nRISct7GH3rgtDlnbTNE2P+v8csiiB3ZRbh1yMxtZvV/7Bft1x",
	"F4Mh3LMxKNJd6bYlNQa9iKbhLNmkejdBARnmlZM0G4QKrbNzXvL8pArtfpuYjwVCzpVCBx7JAxUOEept",
	"wmdDDfC/zgAVJ8vjItG5EACwGi4dnxuLAr7iDKRATXIi0W0d+yhL9MRLC9dvTg8ODl6DcfBJywfwmBst",
	"/DGUlScYI3yTVEgNv/92kKZ+65qBvNOcKhfgPcD5u5PTzuD8ZP/wCMy09vmDf7TyPxxqKJEKI+Kj5VTE",
	"B1/w/cOjvbERsxdDzZL2naoNy1oa3MqwaMXFRuqJ2eX61BnvO2PjRGCbQkfJjdQQOwOGMQMnVxddOFEK",
	"yoo4BamiFtZITR4WGhnqzdAX4xN4RUWgv25ix5ArGdo0UMEJvnFN4NAqPut4PkFwSE6iH2pfmEqJgAC4",
	"hs9bW+PnhRDAaLh6P/jYjdyQpFiFSzICaJawKTpfx5l2+9001IixqLmVLGMH8VWQNRVRkb0CuaLi/+H5",
	"DmPTCO0kor8QLGPni+9bu+h+mm5tooQP1LOKy60dtGWrbabj/dtGubDs5jZhvipL7mYsY5dyihq9B+vM",
	"uF5Ge9N+z9YLwUhGAPWCbnxLAC3raiRgvczftE/WtUlva9mf39adAj3924jZL1vJH9ms583uFObffCcl",
	"/V+GpElXS9JqqCKo62UthbbrVviWvzaCdf+nrF8/23q+qZoaH3BY6ATkMpRW+fS+SzH/YQ38F+kJ/cQ+",
	"FYpq3aXi+GhmbPPH3xPjtpbYowX3F2Y3lGQg/+WfI/8NUl7scA/jMJtqdxvFvjkVb25D3B7ddElsE9el",
	"ybkCgVOWsMqpMBuIbNbrha1RFcZT9ip9lbL57fyPAAAA//9fF5yuvg8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
