version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - nilerr
    - nolintlint
    - revive
    - unconvert
  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: indent-error-flow
        - name: error-return
        - name: error-naming
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
