// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (merchant_id, key_id, secret_hash)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, key_id, secret_hash, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	MerchantID pgtype.UUID
	KeyID      string
	SecretHash []byte
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.MerchantID, arg.KeyID, arg.SecretHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.KeyID,
		&i.SecretHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateMerchant(ctx context.Context, name string) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant, name)
	var i Merchant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getActiveAPIKeyByKeyID = `-- name: GetActiveAPIKeyByKeyID :one
SELECT k.id, k.merchant_id, k.key_id, k.secret_hash, k.created_at, k.revoked_at,
       m.name AS merchant_name
FROM api_keys k
JOIN merchants m ON m.id = k.merchant_id
WHERE k.key_id = $1
  AND k.revoked_at IS NULL
`

type GetActiveAPIKeyByKeyIDRow struct {
	ID           pgtype.UUID
	MerchantID   pgtype.UUID
	KeyID        string
	SecretHash   []byte
	CreatedAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	MerchantName string
}

func (q *Queries) GetActiveAPIKeyByKeyID(ctx context.Context, keyID string) (GetActiveAPIKeyByKeyIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByKeyID, keyID)
	var i GetActiveAPIKeyByKeyIDRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.KeyID,
		&i.SecretHash,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.MerchantName,
	)
	return i, err
}
