// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE created_at < $1
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT merchant_id, key, request_hash, status_code, response_body, created_at FROM idempotency_keys
WHERE merchant_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	MerchantID pgtype.UUID
	Key        string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.MerchantID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.MerchantID,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (merchant_id, key, request_hash, status_code, response_body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (merchant_id, key) DO NOTHING
RETURNING merchant_id, key, request_hash, status_code, response_body, created_at
`

type InsertIdempotencyKeyParams struct {
	MerchantID   pgtype.UUID
	Key          string
	RequestHash  []byte
	StatusCode   int32
	ResponseBody []byte
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.MerchantID,
		arg.Key,
		arg.RequestHash,
		arg.StatusCode,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.MerchantID,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
