// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountBalance = `-- name: AccountBalance :one
SELECT
    a.id,
    a.code,
    a.type,
    a.currency,
    COALESCE(SUM(
        CASE
            WHEN a.type IN ('asset', 'expense') AND p.direction = 'debit'  THEN  p.amount
            WHEN a.type IN ('asset', 'expense') AND p.direction = 'credit' THEN -p.amount
            WHEN a.type IN ('liability', 'equity', 'revenue') AND p.direction = 'credit' THEN  p.amount
            WHEN a.type IN ('liability', 'equity', 'revenue') AND p.direction = 'debit'  THEN -p.amount
        END
    ), 0)::BIGINT AS balance
FROM accounts a
LEFT JOIN postings p ON p.account_id = a.id
WHERE a.id = $1
GROUP BY a.id
`

type AccountBalanceRow struct {
	ID       pgtype.UUID
	Code     string
	Type     AccountType
	Currency string
	Balance  int64
}

// Positive balance is expressed in the account's "natural" direction:
// debit-normal for asset/expense, credit-normal for liability/equity/revenue.
func (q *Queries) AccountBalance(ctx context.Context, id pgtype.UUID) (AccountBalanceRow, error) {
	row := q.db.QueryRow(ctx, accountBalance, id)
	var i AccountBalanceRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Currency,
		&i.Balance,
	)
	return i, err
}

const accountBalanceByCode = `-- name: AccountBalanceByCode :one
SELECT
    a.id,
    a.code,
    a.type,
    a.currency,
    COALESCE(SUM(
        CASE
            WHEN a.type IN ('asset', 'expense') AND p.direction = 'debit'  THEN  p.amount
            WHEN a.type IN ('asset', 'expense') AND p.direction = 'credit' THEN -p.amount
            WHEN a.type IN ('liability', 'equity', 'revenue') AND p.direction = 'credit' THEN  p.amount
            WHEN a.type IN ('liability', 'equity', 'revenue') AND p.direction = 'debit'  THEN -p.amount
        END
    ), 0)::BIGINT AS balance
FROM accounts a
LEFT JOIN postings p ON p.account_id = a.id
WHERE a.code = $1 AND a.currency = $2
GROUP BY a.id
`

type AccountBalanceByCodeParams struct {
	Code     string
	Currency string
}

type AccountBalanceByCodeRow struct {
	ID       pgtype.UUID
	Code     string
	Type     AccountType
	Currency string
	Balance  int64
}

// Variant of AccountBalance keyed on (code, currency) so callers
// without the account UUID at hand (e.g., recon) don't need a
// separate lookup. Returns the same balance shape AccountBalance
// does.
func (q *Queries) AccountBalanceByCode(ctx context.Context, arg AccountBalanceByCodeParams) (AccountBalanceByCodeRow, error) {
	row := q.db.QueryRow(ctx, accountBalanceByCode, arg.Code, arg.Currency)
	var i AccountBalanceByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Currency,
		&i.Balance,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (code, type, currency)
VALUES ($1, $2, $3)
RETURNING id, code, type, currency, created_at
`

type CreateAccountParams struct {
	Code     string
	Type     AccountType
	Currency string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Code, arg.Type, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (external_ref, kind, description, intent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, external_ref, kind, description, intent_id, created_at
`

type CreateJournalEntryParams struct {
	ExternalRef string
	Kind        string
	Description *string
	IntentID    pgtype.UUID
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.ExternalRef,
		arg.Kind,
		arg.Description,
		arg.IntentID,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.ExternalRef,
		&i.Kind,
		&i.Description,
		&i.IntentID,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByCodeCurrency = `-- name: GetAccountByCodeCurrency :one
SELECT id, code, type, currency, created_at FROM accounts WHERE code = $1 AND currency = $2
`

type GetAccountByCodeCurrencyParams struct {
	Code     string
	Currency string
}

func (q *Queries) GetAccountByCodeCurrency(ctx context.Context, arg GetAccountByCodeCurrencyParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByCodeCurrency, arg.Code, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, code, type, currency, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getJournalEntryByExternalRef = `-- name: GetJournalEntryByExternalRef :one
SELECT id, external_ref, kind, description, intent_id, created_at FROM journal_entries WHERE external_ref = $1
`

func (q *Queries) GetJournalEntryByExternalRef(ctx context.Context, externalRef string) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByExternalRef, externalRef)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.ExternalRef,
		&i.Kind,
		&i.Description,
		&i.IntentID,
		&i.CreatedAt,
	)
	return i, err
}

const insertPosting = `-- name: InsertPosting :one
INSERT INTO postings (journal_entry_id, account_id, amount, currency, direction)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, journal_entry_id, account_id, amount, currency, direction, created_at
`

type InsertPostingParams struct {
	JournalEntryID pgtype.UUID
	AccountID      pgtype.UUID
	Amount         int64
	Currency       string
	Direction      PostingDirection
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) (Posting, error) {
	row := q.db.QueryRow(ctx, insertPosting,
		arg.JournalEntryID,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.Direction,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.JournalEntryID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Direction,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, code, type, currency, created_at FROM accounts ORDER BY code, currency
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntriesByIntent = `-- name: ListJournalEntriesByIntent :many
SELECT id, external_ref, kind, description, intent_id, created_at FROM journal_entries WHERE intent_id = $1 ORDER BY created_at
`

func (q *Queries) ListJournalEntriesByIntent(ctx context.Context, intentID pgtype.UUID) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByIntent, intentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.ExternalRef,
			&i.Kind,
			&i.Description,
			&i.IntentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingsByEntry = `-- name: ListPostingsByEntry :many
SELECT id, journal_entry_id, account_id, amount, currency, direction, created_at FROM postings WHERE journal_entry_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListPostingsByEntry(ctx context.Context, journalEntryID pgtype.UUID) ([]Posting, error) {
	rows, err := q.db.Query(ctx, listPostingsByEntry, journalEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Posting{}
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.JournalEntryID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.Direction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
