// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeAsset     AccountType = "asset"
	AccountTypeLiability AccountType = "liability"
	AccountTypeEquity    AccountType = "equity"
	AccountTypeRevenue   AccountType = "revenue"
	AccountTypeExpense   AccountType = "expense"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type PaymentIntentState string

const (
	PaymentIntentStatePending   PaymentIntentState = "pending"
	PaymentIntentStateFunded    PaymentIntentState = "funded"
	PaymentIntentStateSettling  PaymentIntentState = "settling"
	PaymentIntentStatePaidOut   PaymentIntentState = "paid_out"
	PaymentIntentStateCompleted PaymentIntentState = "completed"
	PaymentIntentStateExpired   PaymentIntentState = "expired"
	PaymentIntentStateFailed    PaymentIntentState = "failed"
)

func (e *PaymentIntentState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentIntentState(s)
	case string:
		*e = PaymentIntentState(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentIntentState: %T", src)
	}
	return nil
}

type NullPaymentIntentState struct {
	PaymentIntentState PaymentIntentState
	Valid              bool // Valid is true if PaymentIntentState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentIntentState) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentIntentState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentIntentState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentIntentState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentIntentState), nil
}

type PostingDirection string

const (
	PostingDirectionDebit  PostingDirection = "debit"
	PostingDirectionCredit PostingDirection = "credit"
)

func (e *PostingDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostingDirection(s)
	case string:
		*e = PostingDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for PostingDirection: %T", src)
	}
	return nil
}

type NullPostingDirection struct {
	PostingDirection PostingDirection
	Valid            bool // Valid is true if PostingDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostingDirection) Scan(value interface{}) error {
	if value == nil {
		ns.PostingDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostingDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostingDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostingDirection), nil
}

type SolanaCommitment string

const (
	SolanaCommitmentProcessed SolanaCommitment = "processed"
	SolanaCommitmentConfirmed SolanaCommitment = "confirmed"
	SolanaCommitmentFinalized SolanaCommitment = "finalized"
)

func (e *SolanaCommitment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SolanaCommitment(s)
	case string:
		*e = SolanaCommitment(s)
	default:
		return fmt.Errorf("unsupported scan type for SolanaCommitment: %T", src)
	}
	return nil
}

type NullSolanaCommitment struct {
	SolanaCommitment SolanaCommitment
	Valid            bool // Valid is true if SolanaCommitment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSolanaCommitment) Scan(value interface{}) error {
	if value == nil {
		ns.SolanaCommitment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SolanaCommitment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSolanaCommitment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SolanaCommitment), nil
}

type Account struct {
	ID        pgtype.UUID
	Code      string
	Type      AccountType
	Currency  string
	CreatedAt pgtype.Timestamptz
}

type ApiKey struct {
	ID         pgtype.UUID
	MerchantID pgtype.UUID
	KeyID      string
	SecretHash []byte
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type IdempotencyKey struct {
	MerchantID   pgtype.UUID
	Key          string
	RequestHash  []byte
	StatusCode   int32
	ResponseBody []byte
	CreatedAt    pgtype.Timestamptz
}

type JournalEntry struct {
	ID          pgtype.UUID
	ExternalRef string
	Kind        string
	Description *string
	IntentID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Merchant struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OnchainPayment struct {
	Signature       string
	Slot            int64
	BlockTime       pgtype.Timestamptz
	FromAta         string
	ToAta           string
	Mint            string
	Amount          int64
	ReferencePubkey *string
	Commitment      SolanaCommitment
	IntentID        pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PaymentIntent struct {
	ID                 pgtype.UUID
	MerchantID         pgtype.UUID
	ExternalRef        string
	AmountIdr          int64
	QuotedAmountUsdc   int64
	QuoteID            pgtype.UUID
	ReferencePubkey    *string
	ReferenceSecretEnc []byte
	RecipientAta       *string
	State              PaymentIntentState
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Posting struct {
	ID             pgtype.UUID
	JournalEntryID pgtype.UUID
	AccountID      pgtype.UUID
	Amount         int64
	Currency       string
	Direction      PostingDirection
	CreatedAt      pgtype.Timestamptz
}

type Quote struct {
	ID        pgtype.UUID
	Pair      string
	RateNum   int64
	RateScale int16
	SpreadBps int32
	ExpiresAt pgtype.Timestamptz
	Signature []byte
	CreatedAt pgtype.Timestamptz
}
