// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeAsset     AccountType = "asset"
	AccountTypeLiability AccountType = "liability"
	AccountTypeEquity    AccountType = "equity"
	AccountTypeRevenue   AccountType = "revenue"
	AccountTypeExpense   AccountType = "expense"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type PostingDirection string

const (
	PostingDirectionDebit  PostingDirection = "debit"
	PostingDirectionCredit PostingDirection = "credit"
)

func (e *PostingDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostingDirection(s)
	case string:
		*e = PostingDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for PostingDirection: %T", src)
	}
	return nil
}

type NullPostingDirection struct {
	PostingDirection PostingDirection
	Valid            bool // Valid is true if PostingDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostingDirection) Scan(value interface{}) error {
	if value == nil {
		ns.PostingDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostingDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostingDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostingDirection), nil
}

type Account struct {
	ID        pgtype.UUID
	Code      string
	Type      AccountType
	Currency  string
	CreatedAt pgtype.Timestamptz
}

type IdempotencyKey struct {
	MerchantID   pgtype.UUID
	Key          string
	RequestHash  []byte
	StatusCode   int32
	ResponseBody []byte
	CreatedAt    pgtype.Timestamptz
}

type JournalEntry struct {
	ID          pgtype.UUID
	ExternalRef string
	Kind        string
	Description *string
	IntentID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Posting struct {
	ID             pgtype.UUID
	JournalEntryID pgtype.UUID
	AccountID      pgtype.UUID
	Amount         int64
	Currency       string
	Direction      PostingDirection
	CreatedAt      pgtype.Timestamptz
}
