// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onchain_payments.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOnchainPaymentsByIntent = `-- name: CountOnchainPaymentsByIntent :one
SELECT COUNT(*) FROM onchain_payments WHERE intent_id = $1
`

func (q *Queries) CountOnchainPaymentsByIntent(ctx context.Context, intentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOnchainPaymentsByIntent, intentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFinalizedDepositForIntent = `-- name: GetFinalizedDepositForIntent :one
SELECT signature, slot, block_time, from_ata, to_ata, mint, amount, reference_pubkey, commitment, intent_id, created_at, updated_at FROM onchain_payments
WHERE intent_id = $1 AND commitment = 'finalized'
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetFinalizedDepositForIntent(ctx context.Context, intentID pgtype.UUID) (OnchainPayment, error) {
	row := q.db.QueryRow(ctx, getFinalizedDepositForIntent, intentID)
	var i OnchainPayment
	err := row.Scan(
		&i.Signature,
		&i.Slot,
		&i.BlockTime,
		&i.FromAta,
		&i.ToAta,
		&i.Mint,
		&i.Amount,
		&i.ReferencePubkey,
		&i.Commitment,
		&i.IntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOnchainPaymentBySignature = `-- name: GetOnchainPaymentBySignature :one
SELECT signature, slot, block_time, from_ata, to_ata, mint, amount, reference_pubkey, commitment, intent_id, created_at, updated_at FROM onchain_payments WHERE signature = $1
`

func (q *Queries) GetOnchainPaymentBySignature(ctx context.Context, signature string) (OnchainPayment, error) {
	row := q.db.QueryRow(ctx, getOnchainPaymentBySignature, signature)
	var i OnchainPayment
	err := row.Scan(
		&i.Signature,
		&i.Slot,
		&i.BlockTime,
		&i.FromAta,
		&i.ToAta,
		&i.Mint,
		&i.Amount,
		&i.ReferencePubkey,
		&i.Commitment,
		&i.IntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOnchainPaymentsByIntent = `-- name: ListOnchainPaymentsByIntent :many
SELECT signature, slot, block_time, from_ata, to_ata, mint, amount, reference_pubkey, commitment, intent_id, created_at, updated_at FROM onchain_payments
WHERE intent_id = $1
ORDER BY created_at
`

func (q *Queries) ListOnchainPaymentsByIntent(ctx context.Context, intentID pgtype.UUID) ([]OnchainPayment, error) {
	rows, err := q.db.Query(ctx, listOnchainPaymentsByIntent, intentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnchainPayment{}
	for rows.Next() {
		var i OnchainPayment
		if err := rows.Scan(
			&i.Signature,
			&i.Slot,
			&i.BlockTime,
			&i.FromAta,
			&i.ToAta,
			&i.Mint,
			&i.Amount,
			&i.ReferencePubkey,
			&i.Commitment,
			&i.IntentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinalizedOnchainPayments = `-- name: ListUnfinalizedOnchainPayments :many
SELECT signature, slot, block_time, from_ata, to_ata, mint, amount, reference_pubkey, commitment, intent_id, created_at, updated_at FROM onchain_payments
WHERE commitment <> 'finalized'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListUnfinalizedOnchainPayments(ctx context.Context, limit int32) ([]OnchainPayment, error) {
	rows, err := q.db.Query(ctx, listUnfinalizedOnchainPayments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnchainPayment{}
	for rows.Next() {
		var i OnchainPayment
		if err := rows.Scan(
			&i.Signature,
			&i.Slot,
			&i.BlockTime,
			&i.FromAta,
			&i.ToAta,
			&i.Mint,
			&i.Amount,
			&i.ReferencePubkey,
			&i.Commitment,
			&i.IntentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOnchainPayment = `-- name: UpsertOnchainPayment :one
INSERT INTO onchain_payments (
    signature, slot, block_time, from_ata, to_ata, mint, amount,
    reference_pubkey, commitment, intent_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (signature) DO UPDATE SET
    commitment = CASE
        WHEN onchain_payments.commitment < EXCLUDED.commitment THEN EXCLUDED.commitment
        ELSE onchain_payments.commitment
    END,
    intent_id = COALESCE(onchain_payments.intent_id, EXCLUDED.intent_id),
    updated_at = NOW()
RETURNING signature, slot, block_time, from_ata, to_ata, mint, amount, reference_pubkey, commitment, intent_id, created_at, updated_at
`

type UpsertOnchainPaymentParams struct {
	Signature       string
	Slot            int64
	BlockTime       pgtype.Timestamptz
	FromAta         string
	ToAta           string
	Mint            string
	Amount          int64
	ReferencePubkey *string
	Commitment      SolanaCommitment
	IntentID        pgtype.UUID
}

func (q *Queries) UpsertOnchainPayment(ctx context.Context, arg UpsertOnchainPaymentParams) (OnchainPayment, error) {
	row := q.db.QueryRow(ctx, upsertOnchainPayment,
		arg.Signature,
		arg.Slot,
		arg.BlockTime,
		arg.FromAta,
		arg.ToAta,
		arg.Mint,
		arg.Amount,
		arg.ReferencePubkey,
		arg.Commitment,
		arg.IntentID,
	)
	var i OnchainPayment
	err := row.Scan(
		&i.Signature,
		&i.Slot,
		&i.BlockTime,
		&i.FromAta,
		&i.ToAta,
		&i.Mint,
		&i.Amount,
		&i.ReferencePubkey,
		&i.Commitment,
		&i.IntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
