// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueOutbox = `-- name: ClaimDueOutbox :many
SELECT id, topic, aggregate_id, payload, headers, created_at, next_attempt_at, delivered_at, attempts, last_error
FROM outbox
WHERE topic = $1
  AND delivered_at IS NULL
  AND next_attempt_at <= NOW()
ORDER BY next_attempt_at
FOR UPDATE SKIP LOCKED
LIMIT $2
`

type ClaimDueOutboxParams struct {
	Topic string
	Limit int32
}

// Pulls a batch of undelivered messages whose backoff window has elapsed.
// Caller is expected to hold a pg_try_advisory_lock on the topic so only
// one dispatcher process drains it; SKIP LOCKED is still here for safety
// in case two dispatchers race the lock. Ordered by next_attempt_at to
// preserve fair retry sequencing.
func (q *Queries) ClaimDueOutbox(ctx context.Context, arg ClaimDueOutboxParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimDueOutbox, arg.Topic, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.AggregateID,
			&i.Payload,
			&i.Headers,
			&i.CreatedAt,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutboxByID = `-- name: GetOutboxByID :one
SELECT id, topic, aggregate_id, payload, headers, created_at, next_attempt_at, delivered_at, attempts, last_error FROM outbox WHERE id = $1
`

func (q *Queries) GetOutboxByID(ctx context.Context, id pgtype.UUID) (Outbox, error) {
	row := q.db.QueryRow(ctx, getOutboxByID, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.AggregateID,
		&i.Payload,
		&i.Headers,
		&i.CreatedAt,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}

const listOutboxByAggregate = `-- name: ListOutboxByAggregate :many
SELECT id, topic, aggregate_id, payload, headers, created_at, next_attempt_at, delivered_at, attempts, last_error FROM outbox
WHERE aggregate_id = $1
ORDER BY created_at
`

func (q *Queries) ListOutboxByAggregate(ctx context.Context, aggregateID pgtype.UUID) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, listOutboxByAggregate, aggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.AggregateID,
			&i.Payload,
			&i.Headers,
			&i.CreatedAt,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUndeliveredOutbox = `-- name: ListUndeliveredOutbox :many
SELECT id, topic, aggregate_id, payload, headers, created_at, next_attempt_at, delivered_at, attempts, last_error FROM outbox
WHERE delivered_at IS NULL
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListUndeliveredOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, listUndeliveredOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.AggregateID,
			&i.Payload,
			&i.Headers,
			&i.CreatedAt,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :one
UPDATE outbox
SET delivered_at = NOW(),
    last_error   = NULL
WHERE id = $1
RETURNING id, topic, aggregate_id, payload, headers, created_at, next_attempt_at, delivered_at, attempts, last_error
`

func (q *Queries) MarkOutboxDelivered(ctx context.Context, id pgtype.UUID) (Outbox, error) {
	row := q.db.QueryRow(ctx, markOutboxDelivered, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.AggregateID,
		&i.Payload,
		&i.Headers,
		&i.CreatedAt,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}

const publishOutbox = `-- name: PublishOutbox :one
INSERT INTO outbox (topic, aggregate_id, payload, headers)
VALUES ($1, $2, $3, $4)
RETURNING id, topic, aggregate_id, payload, headers, created_at, next_attempt_at, delivered_at, attempts, last_error
`

type PublishOutboxParams struct {
	Topic       string
	AggregateID pgtype.UUID
	Payload     []byte
	Headers     []byte
}

func (q *Queries) PublishOutbox(ctx context.Context, arg PublishOutboxParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, publishOutbox,
		arg.Topic,
		arg.AggregateID,
		arg.Payload,
		arg.Headers,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.AggregateID,
		&i.Payload,
		&i.Headers,
		&i.CreatedAt,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}

const scheduleOutboxRetry = `-- name: ScheduleOutboxRetry :one
UPDATE outbox
SET attempts        = attempts + 1,
    next_attempt_at = $2,
    last_error      = $3
WHERE id = $1
RETURNING id, topic, aggregate_id, payload, headers, created_at, next_attempt_at, delivered_at, attempts, last_error
`

type ScheduleOutboxRetryParams struct {
	ID            pgtype.UUID
	NextAttemptAt pgtype.Timestamptz
	LastError     *string
}

func (q *Queries) ScheduleOutboxRetry(ctx context.Context, arg ScheduleOutboxRetryParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, scheduleOutboxRetry, arg.ID, arg.NextAttemptAt, arg.LastError)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.AggregateID,
		&i.Payload,
		&i.Headers,
		&i.CreatedAt,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}
