// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_intents.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentIntent = `-- name: CreatePaymentIntent :one
INSERT INTO payment_intents (
    merchant_id, external_ref, amount_idr, quoted_amount_usdc, quote_id, state,
    reference_pubkey, reference_secret_enc, recipient_ata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, merchant_id, external_ref, amount_idr, quoted_amount_usdc, quote_id, reference_pubkey, reference_secret_enc, recipient_ata, state, created_at, updated_at
`

type CreatePaymentIntentParams struct {
	MerchantID         pgtype.UUID
	ExternalRef        string
	AmountIdr          int64
	QuotedAmountUsdc   int64
	QuoteID            pgtype.UUID
	State              PaymentIntentState
	ReferencePubkey    *string
	ReferenceSecretEnc []byte
	RecipientAta       *string
}

func (q *Queries) CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, createPaymentIntent,
		arg.MerchantID,
		arg.ExternalRef,
		arg.AmountIdr,
		arg.QuotedAmountUsdc,
		arg.QuoteID,
		arg.State,
		arg.ReferencePubkey,
		arg.ReferenceSecretEnc,
		arg.RecipientAta,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalRef,
		&i.AmountIdr,
		&i.QuotedAmountUsdc,
		&i.QuoteID,
		&i.ReferencePubkey,
		&i.ReferenceSecretEnc,
		&i.RecipientAta,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentIntentByID = `-- name: GetPaymentIntentByID :one
SELECT id, merchant_id, external_ref, amount_idr, quoted_amount_usdc, quote_id, reference_pubkey, reference_secret_enc, recipient_ata, state, created_at, updated_at FROM payment_intents WHERE id = $1
`

func (q *Queries) GetPaymentIntentByID(ctx context.Context, id pgtype.UUID) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByID, id)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalRef,
		&i.AmountIdr,
		&i.QuotedAmountUsdc,
		&i.QuoteID,
		&i.ReferencePubkey,
		&i.ReferenceSecretEnc,
		&i.RecipientAta,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentIntentByMerchantRef = `-- name: GetPaymentIntentByMerchantRef :one
SELECT id, merchant_id, external_ref, amount_idr, quoted_amount_usdc, quote_id, reference_pubkey, reference_secret_enc, recipient_ata, state, created_at, updated_at FROM payment_intents
WHERE merchant_id = $1 AND external_ref = $2
`

type GetPaymentIntentByMerchantRefParams struct {
	MerchantID  pgtype.UUID
	ExternalRef string
}

func (q *Queries) GetPaymentIntentByMerchantRef(ctx context.Context, arg GetPaymentIntentByMerchantRefParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByMerchantRef, arg.MerchantID, arg.ExternalRef)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalRef,
		&i.AmountIdr,
		&i.QuotedAmountUsdc,
		&i.QuoteID,
		&i.ReferencePubkey,
		&i.ReferenceSecretEnc,
		&i.RecipientAta,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveReferenceIntents = `-- name: ListActiveReferenceIntents :many
SELECT id, reference_pubkey
FROM payment_intents
WHERE state IN ('pending', 'funded')
  AND reference_pubkey IS NOT NULL
ORDER BY created_at
`

type ListActiveReferenceIntentsRow struct {
	ID              pgtype.UUID
	ReferencePubkey *string
}

func (q *Queries) ListActiveReferenceIntents(ctx context.Context) ([]ListActiveReferenceIntentsRow, error) {
	rows, err := q.db.Query(ctx, listActiveReferenceIntents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveReferenceIntentsRow{}
	for rows.Next() {
		var i ListActiveReferenceIntentsRow
		if err := rows.Scan(&i.ID, &i.ReferencePubkey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentIntentReference = `-- name: UpdatePaymentIntentReference :one
UPDATE payment_intents
SET reference_pubkey = $2,
    reference_secret_enc = $3,
    recipient_ata = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, merchant_id, external_ref, amount_idr, quoted_amount_usdc, quote_id, reference_pubkey, reference_secret_enc, recipient_ata, state, created_at, updated_at
`

type UpdatePaymentIntentReferenceParams struct {
	ID                 pgtype.UUID
	ReferencePubkey    *string
	ReferenceSecretEnc []byte
	RecipientAta       *string
}

func (q *Queries) UpdatePaymentIntentReference(ctx context.Context, arg UpdatePaymentIntentReferenceParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, updatePaymentIntentReference,
		arg.ID,
		arg.ReferencePubkey,
		arg.ReferenceSecretEnc,
		arg.RecipientAta,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalRef,
		&i.AmountIdr,
		&i.QuotedAmountUsdc,
		&i.QuoteID,
		&i.ReferencePubkey,
		&i.ReferenceSecretEnc,
		&i.RecipientAta,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentIntentState = `-- name: UpdatePaymentIntentState :one
UPDATE payment_intents
SET state = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, merchant_id, external_ref, amount_idr, quoted_amount_usdc, quote_id, reference_pubkey, reference_secret_enc, recipient_ata, state, created_at, updated_at
`

type UpdatePaymentIntentStateParams struct {
	ID    pgtype.UUID
	State PaymentIntentState
}

func (q *Queries) UpdatePaymentIntentState(ctx context.Context, arg UpdatePaymentIntentStateParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, updatePaymentIntentState, arg.ID, arg.State)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalRef,
		&i.AmountIdr,
		&i.QuotedAmountUsdc,
		&i.QuoteID,
		&i.ReferencePubkey,
		&i.ReferenceSecretEnc,
		&i.RecipientAta,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
