// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payouts.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPayoutByIntent = `-- name: GetPayoutByIntent :one
SELECT id, intent_id, rail, amount_idr, state, rail_reference, last_error, attempts, created_at, updated_at FROM payouts WHERE intent_id = $1
`

func (q *Queries) GetPayoutByIntent(ctx context.Context, intentID pgtype.UUID) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayoutByIntent, intentID)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Rail,
		&i.AmountIdr,
		&i.State,
		&i.RailReference,
		&i.LastError,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPayoutFailed = `-- name: MarkPayoutFailed :one
UPDATE payouts
SET state      = 'failed',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, intent_id, rail, amount_idr, state, rail_reference, last_error, attempts, created_at, updated_at
`

type MarkPayoutFailedParams struct {
	ID        pgtype.UUID
	LastError *string
}

func (q *Queries) MarkPayoutFailed(ctx context.Context, arg MarkPayoutFailedParams) (Payout, error) {
	row := q.db.QueryRow(ctx, markPayoutFailed, arg.ID, arg.LastError)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Rail,
		&i.AmountIdr,
		&i.State,
		&i.RailReference,
		&i.LastError,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPayoutSubmitting = `-- name: MarkPayoutSubmitting :one
UPDATE payouts
SET state      = 'submitting',
    attempts   = attempts + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, intent_id, rail, amount_idr, state, rail_reference, last_error, attempts, created_at, updated_at
`

func (q *Queries) MarkPayoutSubmitting(ctx context.Context, id pgtype.UUID) (Payout, error) {
	row := q.db.QueryRow(ctx, markPayoutSubmitting, id)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Rail,
		&i.AmountIdr,
		&i.State,
		&i.RailReference,
		&i.LastError,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPayoutSucceeded = `-- name: MarkPayoutSucceeded :one
UPDATE payouts
SET state          = 'succeeded',
    rail_reference = $2,
    last_error     = NULL,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, intent_id, rail, amount_idr, state, rail_reference, last_error, attempts, created_at, updated_at
`

type MarkPayoutSucceededParams struct {
	ID            pgtype.UUID
	RailReference *string
}

func (q *Queries) MarkPayoutSucceeded(ctx context.Context, arg MarkPayoutSucceededParams) (Payout, error) {
	row := q.db.QueryRow(ctx, markPayoutSucceeded, arg.ID, arg.RailReference)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Rail,
		&i.AmountIdr,
		&i.State,
		&i.RailReference,
		&i.LastError,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetPayoutToPending = `-- name: ResetPayoutToPending :one
UPDATE payouts
SET state      = 'pending',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, intent_id, rail, amount_idr, state, rail_reference, last_error, attempts, created_at, updated_at
`

type ResetPayoutToPendingParams struct {
	ID        pgtype.UUID
	LastError *string
}

func (q *Queries) ResetPayoutToPending(ctx context.Context, arg ResetPayoutToPendingParams) (Payout, error) {
	row := q.db.QueryRow(ctx, resetPayoutToPending, arg.ID, arg.LastError)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Rail,
		&i.AmountIdr,
		&i.State,
		&i.RailReference,
		&i.LastError,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPayout = `-- name: UpsertPayout :one
INSERT INTO payouts (intent_id, rail, amount_idr, state)
VALUES ($1, $2, $3, 'pending')
ON CONFLICT (intent_id) DO UPDATE SET intent_id = EXCLUDED.intent_id
RETURNING id, intent_id, rail, amount_idr, state, rail_reference, last_error, attempts, created_at, updated_at
`

type UpsertPayoutParams struct {
	IntentID  pgtype.UUID
	Rail      string
	AmountIdr int64
}

// Creates the payout row on first call, returns the existing row on
// replay. The ON CONFLICT branch updates intent_id to itself so
// RETURNING * fires consistently — the caller never has to follow up
// with a SELECT to learn the persisted state.
func (q *Queries) UpsertPayout(ctx context.Context, arg UpsertPayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, upsertPayout, arg.IntentID, arg.Rail, arg.AmountIdr)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Rail,
		&i.AmountIdr,
		&i.State,
		&i.RailReference,
		&i.LastError,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
