// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Positive balance is expressed in the account's "natural" direction:
	// debit-normal for asset/expense, credit-normal for liability/equity/revenue.
	AccountBalance(ctx context.Context, id pgtype.UUID) (AccountBalanceRow, error)
	CountOnchainPaymentsByIntent(ctx context.Context, intentID pgtype.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error)
	CreateMerchant(ctx context.Context, name string) (Merchant, error)
	CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentIntent, error)
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	GetAccountByCodeCurrency(ctx context.Context, arg GetAccountByCodeCurrencyParams) (Account, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetActiveAPIKeyByKeyID(ctx context.Context, keyID string) (GetActiveAPIKeyByKeyIDRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetJournalEntryByExternalRef(ctx context.Context, externalRef string) (JournalEntry, error)
	GetOnchainPaymentBySignature(ctx context.Context, signature string) (OnchainPayment, error)
	GetPaymentIntentByID(ctx context.Context, id pgtype.UUID) (PaymentIntent, error)
	GetPaymentIntentByMerchantRef(ctx context.Context, arg GetPaymentIntentByMerchantRefParams) (PaymentIntent, error)
	GetQuote(ctx context.Context, id pgtype.UUID) (Quote, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error)
	InsertPosting(ctx context.Context, arg InsertPostingParams) (Posting, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListActiveReferenceIntents(ctx context.Context) ([]ListActiveReferenceIntentsRow, error)
	ListPostingsByEntry(ctx context.Context, journalEntryID pgtype.UUID) ([]Posting, error)
	ListUnfinalizedOnchainPayments(ctx context.Context, limit int32) ([]OnchainPayment, error)
	UpdatePaymentIntentReference(ctx context.Context, arg UpdatePaymentIntentReferenceParams) (PaymentIntent, error)
	UpdatePaymentIntentState(ctx context.Context, arg UpdatePaymentIntentStateParams) (PaymentIntent, error)
	UpsertOnchainPayment(ctx context.Context, arg UpsertOnchainPaymentParams) (OnchainPayment, error)
}

var _ Querier = (*Queries)(nil)
