// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Positive balance is expressed in the account's "natural" direction:
	// debit-normal for asset/expense, credit-normal for liability/equity/revenue.
	AccountBalance(ctx context.Context, id pgtype.UUID) (AccountBalanceRow, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	GetAccountByCodeCurrency(ctx context.Context, arg GetAccountByCodeCurrencyParams) (Account, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetJournalEntryByExternalRef(ctx context.Context, externalRef string) (JournalEntry, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error)
	InsertPosting(ctx context.Context, arg InsertPostingParams) (Posting, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListPostingsByEntry(ctx context.Context, journalEntryID pgtype.UUID) ([]Posting, error)
}

var _ Querier = (*Queries)(nil)
