// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (pair, rate_num, rate_scale, spread_bps, expires_at, signature)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, pair, rate_num, rate_scale, spread_bps, expires_at, signature, created_at
`

type CreateQuoteParams struct {
	Pair      string
	RateNum   int64
	RateScale int16
	SpreadBps int32
	ExpiresAt pgtype.Timestamptz
	Signature []byte
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.Pair,
		arg.RateNum,
		arg.RateScale,
		arg.SpreadBps,
		arg.ExpiresAt,
		arg.Signature,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Pair,
		&i.RateNum,
		&i.RateScale,
		&i.SpreadBps,
		&i.ExpiresAt,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, pair, rate_num, rate_scale, spread_bps, expires_at, signature, created_at FROM quotes WHERE id = $1
`

func (q *Queries) GetQuote(ctx context.Context, id pgtype.UUID) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Pair,
		&i.RateNum,
		&i.RateScale,
		&i.SpreadBps,
		&i.ExpiresAt,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}
