// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saga_runs.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSagaStep = `-- name: AdvanceSagaStep :one
UPDATE saga_runs
SET current_step  = $2,
    state         = 'pending',
    step_attempts = 0,
    next_run_at   = NOW(),
    lease_owner   = NULL,
    lease_until   = NULL,
    last_error    = NULL,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, intent_id, saga_kind, current_step, state, step_attempts, next_run_at, lease_owner, lease_until, last_error, created_at, updated_at
`

type AdvanceSagaStepParams struct {
	ID          pgtype.UUID
	CurrentStep string
}

// Step succeeded and the saga has more work to do. Resets attempts and
// releases the lease so the next worker can pick it up immediately.
func (q *Queries) AdvanceSagaStep(ctx context.Context, arg AdvanceSagaStepParams) (SagaRun, error) {
	row := q.db.QueryRow(ctx, advanceSagaStep, arg.ID, arg.CurrentStep)
	var i SagaRun
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.SagaKind,
		&i.CurrentStep,
		&i.State,
		&i.StepAttempts,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimDueSagaRun = `-- name: ClaimDueSagaRun :one
WITH next AS (
    SELECT id
    FROM saga_runs
    WHERE state IN ('pending', 'running')
      AND next_run_at <= NOW()
      AND (lease_until IS NULL OR lease_until < NOW())
    ORDER BY next_run_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE saga_runs s
SET state       = 'running',
    lease_owner = $1::TEXT,
    lease_until = NOW() + make_interval(secs => $2::DOUBLE PRECISION),
    updated_at  = NOW()
FROM next
WHERE s.id = next.id
RETURNING s.id, s.intent_id, s.saga_kind, s.current_step, s.state, s.step_attempts, s.next_run_at, s.lease_owner, s.lease_until, s.last_error, s.created_at, s.updated_at
`

type ClaimDueSagaRunParams struct {
	LeaseOwner   string
	LeaseSeconds float64
}

// Claims one due saga and stamps a time-bound lease on it. SKIP LOCKED lets
// N orchestrator workers run side by side without contention; expired
// leases are reclaimable so a worker crashing mid-step doesn't strand the
// saga. Returns no rows when nothing is due — the runner uses pgx.ErrNoRows
// as its idle signal.
func (q *Queries) ClaimDueSagaRun(ctx context.Context, arg ClaimDueSagaRunParams) (SagaRun, error) {
	row := q.db.QueryRow(ctx, claimDueSagaRun, arg.LeaseOwner, arg.LeaseSeconds)
	var i SagaRun
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.SagaKind,
		&i.CurrentStep,
		&i.State,
		&i.StepAttempts,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeSagaRun = `-- name: CompleteSagaRun :one
UPDATE saga_runs
SET state       = 'completed',
    lease_owner = NULL,
    lease_until = NULL,
    last_error  = NULL,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, intent_id, saga_kind, current_step, state, step_attempts, next_run_at, lease_owner, lease_until, last_error, created_at, updated_at
`

func (q *Queries) CompleteSagaRun(ctx context.Context, id pgtype.UUID) (SagaRun, error) {
	row := q.db.QueryRow(ctx, completeSagaRun, id)
	var i SagaRun
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.SagaKind,
		&i.CurrentStep,
		&i.State,
		&i.StepAttempts,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueSagaRun = `-- name: EnqueueSagaRun :one
INSERT INTO saga_runs (intent_id, saga_kind, current_step, state, next_run_at)
VALUES ($1, $2, $3, 'pending', NOW())
ON CONFLICT (intent_id, saga_kind) DO UPDATE SET intent_id = EXCLUDED.intent_id
RETURNING id, intent_id, saga_kind, current_step, state, step_attempts, next_run_at, lease_owner, lease_until, last_error, created_at, updated_at
`

type EnqueueSagaRunParams struct {
	IntentID    pgtype.UUID
	SagaKind    string
	CurrentStep string
}

// Idempotent saga insert keyed on (intent_id, saga_kind). The ON CONFLICT
// branch is a no-op update of intent_id (a value it already equals), which
// forces RETURNING * to fire on conflict — letting the caller treat enqueue
// and re-enqueue with the same return shape and never have to follow up
// with a SELECT.
func (q *Queries) EnqueueSagaRun(ctx context.Context, arg EnqueueSagaRunParams) (SagaRun, error) {
	row := q.db.QueryRow(ctx, enqueueSagaRun, arg.IntentID, arg.SagaKind, arg.CurrentStep)
	var i SagaRun
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.SagaKind,
		&i.CurrentStep,
		&i.State,
		&i.StepAttempts,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failSagaRun = `-- name: FailSagaRun :one
UPDATE saga_runs
SET state       = 'failed',
    lease_owner = NULL,
    lease_until = NULL,
    last_error  = $2,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, intent_id, saga_kind, current_step, state, step_attempts, next_run_at, lease_owner, lease_until, last_error, created_at, updated_at
`

type FailSagaRunParams struct {
	ID        pgtype.UUID
	LastError *string
}

func (q *Queries) FailSagaRun(ctx context.Context, arg FailSagaRunParams) (SagaRun, error) {
	row := q.db.QueryRow(ctx, failSagaRun, arg.ID, arg.LastError)
	var i SagaRun
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.SagaKind,
		&i.CurrentStep,
		&i.State,
		&i.StepAttempts,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaRunByID = `-- name: GetSagaRunByID :one
SELECT id, intent_id, saga_kind, current_step, state, step_attempts, next_run_at, lease_owner, lease_until, last_error, created_at, updated_at FROM saga_runs WHERE id = $1
`

func (q *Queries) GetSagaRunByID(ctx context.Context, id pgtype.UUID) (SagaRun, error) {
	row := q.db.QueryRow(ctx, getSagaRunByID, id)
	var i SagaRun
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.SagaKind,
		&i.CurrentStep,
		&i.State,
		&i.StepAttempts,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaRunByIntent = `-- name: GetSagaRunByIntent :one
SELECT id, intent_id, saga_kind, current_step, state, step_attempts, next_run_at, lease_owner, lease_until, last_error, created_at, updated_at FROM saga_runs WHERE intent_id = $1 AND saga_kind = $2
`

type GetSagaRunByIntentParams struct {
	IntentID pgtype.UUID
	SagaKind string
}

func (q *Queries) GetSagaRunByIntent(ctx context.Context, arg GetSagaRunByIntentParams) (SagaRun, error) {
	row := q.db.QueryRow(ctx, getSagaRunByIntent, arg.IntentID, arg.SagaKind)
	var i SagaRun
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.SagaKind,
		&i.CurrentStep,
		&i.State,
		&i.StepAttempts,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSagaRunsByState = `-- name: ListSagaRunsByState :many
SELECT id, intent_id, saga_kind, current_step, state, step_attempts, next_run_at, lease_owner, lease_until, last_error, created_at, updated_at FROM saga_runs WHERE state = $1 ORDER BY created_at DESC LIMIT $2
`

type ListSagaRunsByStateParams struct {
	State SagaState
	Limit int32
}

func (q *Queries) ListSagaRunsByState(ctx context.Context, arg ListSagaRunsByStateParams) ([]SagaRun, error) {
	rows, err := q.db.Query(ctx, listSagaRunsByState, arg.State, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SagaRun{}
	for rows.Next() {
		var i SagaRun
		if err := rows.Scan(
			&i.ID,
			&i.IntentID,
			&i.SagaKind,
			&i.CurrentStep,
			&i.State,
			&i.StepAttempts,
			&i.NextRunAt,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleSagaRetry = `-- name: ScheduleSagaRetry :one
UPDATE saga_runs
SET step_attempts = step_attempts + 1,
    state         = 'pending',
    next_run_at   = $2,
    lease_owner   = NULL,
    lease_until   = NULL,
    last_error    = $3,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, intent_id, saga_kind, current_step, state, step_attempts, next_run_at, lease_owner, lease_until, last_error, created_at, updated_at
`

type ScheduleSagaRetryParams struct {
	ID        pgtype.UUID
	NextRunAt pgtype.Timestamptz
	LastError *string
}

// Step failed but is retryable. Caller computes next_run_at from the attempt
// count using exponential backoff with jitter; storing the absolute time
// means dispatcher restarts cannot reset the schedule.
func (q *Queries) ScheduleSagaRetry(ctx context.Context, arg ScheduleSagaRetryParams) (SagaRun, error) {
	row := q.db.QueryRow(ctx, scheduleSagaRetry, arg.ID, arg.NextRunAt, arg.LastError)
	var i SagaRun
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.SagaKind,
		&i.CurrentStep,
		&i.State,
		&i.StepAttempts,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
